This example shows that numpy slicing have shallow copy, as its built for speed.
Need to ensure this is handled during any slicing and updating.

In [1]:
import numpy as np

In [14]:
myArr = np.arange(10)
myArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arrSlice = myArr[5:8]
arrSlice

array([5, 6, 7])

In [16]:
arrSlice[1] = 1
arrSlice

array([5, 1, 7])

In [18]:
arrSlice[:] = 64
arrSlice

array([64, 64, 64])

In [19]:
myArr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])