In [71]:
import numpy as np
import sklearn.preprocessing

In [72]:
input_data = np.array([[1.5, -2.0, 5.5],
[-2.5, 2.4, 4.5],
[0.5, -8.0, 5.0],
[6.9, 2.0, -5.2]])

In [73]:
binarizer = sklearn.preprocessing.Binarizer(threshold = 0.5)

In [74]:
data_binarized = binarizer.transform(input_data)

In [75]:
print("\nBinarized data:\n", data_binarized)


Binarized data:
 [[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]
